// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
			/// <summary>
			/// Tag: Music
			/// 2D
			/// </summary>
			public const string Music = "Music";

			/// <summary>
			/// Tag: SFX
			/// 2D
			/// </summary>
			public const string SFX = "SFX";

		}

		public class Variables
		{
			/// <summary>
			/// Variable: MusicVar
			/// Range: [0 - 6]
			/// Type: Local
			/// </summary>
			public const string MusicVar = "MusicVar";

			/// <summary>
			/// Variable: SFXVar
			/// Range: [0 - 7]
			/// Type: Local
			/// </summary>
			public const string SFXVar = "SFXVar";

		}

		public class Channels
		{
			public const string Master = "Master";

		}
	}
}
